### ISSUE TITLE
These varaiable are not intialized

### ISSUE THREAD

**Issue by weiyuan-jiang** [GEOS-ESM/GEOSgcm_GridComp#575] opened 2022-04-05 20:43 UTC
https://github.com/GEOS-ESM/GEOSgcm_GridComp/blob/ba7135a18a955e32b879a83cb72bea2b1c05d0d1/GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/mk_restarts/mk_GEOSldasRestarts.F90#L1563-L1566

When there exists catchcn_params.nc4 in the boundary directory, these variables are not initialized. Does catchcn_paranms.nc4 only exist in newland? if so, we need to read CLM4.5_veg_typs_fracs too.  @gmao-rreichle

**Comment by gmao-rreichle** [comment] 2022-04-05 21:01
@weiyuan-jiang: Sorry, I can't answer this quickly and don't have the time to investigate for another day or two.  
I don't think CatchCN bcs are limited to "newland", but I don't know for sure and might well be wrong. 
Perhaps @gmao-jkolassa can weight in?

**Comment by gmao-jkolassa** [comment] 2022-04-05 21:21
I am not sure I have a very good answer to this either. I can say that all CatchCN simulations that we have run (including the initial simulations by Fanwei) have used new land boundary conditions. But I am not sure whether that means CatchCN cannot be used with old land boundary conditions.

**Comment by weiyuan-jiang** [comment] 2022-04-05 21:22
@gmao-jkolassa , After many calculations, those variables are forgotten and not used .

**Comment by gmao-rreichle** [comment] 2022-04-05 21:33
> I am not sure I have a very good answer to this either. I can say that all CatchCN simulations that we have run (including the initial simulations by Fanwei) have used new land boundary conditions. 

Thanks, @gmao-jkolassa.  If all CatchCN work is with "newland" bcs, then there's no need to support the "oldland" bcs for CatchCN in mk_restarts.  

I don't recall if make_bcs can create "oldland" bcs for CatchCN.  If it does, these bcs would not be needed. 

I suggest making it explicit in the mk_restarts and make_bcs scripts and programs that "oldland" bcs are **not** supported for CatchCN.  

cc: @biljanaorescanin @rdkoster

**Comment by gmao-jkolassa** [comment] 2022-04-07 21:30
Hi @weiyuan-jiang ,

@gmao-rreichle and I talked a bit more about this issue this afternoon and he told me about your concerns. I looked into it a little bit and it seems that the problematic code you found is a remnant from when Fanwei and Sarith initially tried to implement the use of the CLM45 PFT distribution, which is different from the CLM40 PFT distribution. At some point they decided to abandon this effort and instead use the CLM40 PFT distribution for CNCLM45. That means all the `if (clm45) `statements and the calculations for ` CLMC45_pf1` are obsolete and can be removed. I will go through mk_GEOSldasRestarts.F90 and clean this up and also check for any other places where CLM4.5_veg_typs_fracs is read.

I will make a PR to be merged into branch _feature/rreichle/mk_restarts_cleanup_. Before I get started I wanted to ask whether the version of _feature/rreichle/mk_restarts_cleanup_ that is currently on Github is a good one to work from or whether there are any commits you would like to push before I check out the branch?

Thanks!

**Comment by gmao-rreichle** [comment] 2022-04-07 21:40
Thanks, @gmao-jkolassa!  If it turns out that we indeed do not use `CLM4.5_veg_typs_fracs` at all, then we may need to amend the documentation in the make_bcs package (`GEOSsurface_GridComp/Utils/Raster/`).
If my understanding of the issue is correct, the veg class in CNCLM45 restart files matches that of `CLM_veg_typs_fracs` and **not** that of `CLM4.5_veg_typs_fracs`.  Having the latter file in the bcs directory but not used for CNCLM45 is utterly confusing.     We may even want to remove `CLM4.5_veg_typs_fracs` from the bcs package or change its name or location to something that better indicates that the file is not used.  
cc: @rdkoster @biljanaorescanin

**Comment by gmao-rreichle** [comment] 2022-05-06 13:54
@gmao-jkolassa, @weiyuan-jiang,

Re. aborted PR https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/584:

> CNCLM40 and CNCLM45 were initially supposed to have different plant functional type (PFT) distributions, hence the reason why different files were read. At some point the decision was made to use the same PFT distribution for both models, ...
> This means that the parts of the code that read CLM4.5_veg_typs_fracs and all calculations involving CLMC45_XXX are obsolete and can be removed. 

This just underlines the importance of cleaning up the relevant source code and also including the essence of Jana's comments in the source code, incl. in the make_bcs package.   We need to document the intent for future reference so we don't keep stumbling over the same thing.  @gmao-jkolassa, please create a new branch and PR that specifically addresses this cleanup and documentation. 

cc: @rdkoster @biljanaorescanin

**Comment by weiyuan-jiang** [comment] 2022-05-06 15:30
@gmao-rreichle I have removed all those leftover  in our new branch. [ ](https://github.com/GEOS-ESM/GEOSgcm_GridComp/tree/feature/rreichle/mk_restarts_cleanup) . I think we  don't need other branch any more @gmao-jkolassa

**Comment by gmao-rreichle** [comment] 2022-05-06 15:52
> I have removed all those leftover in our new branch.  I think we don't need other branch any more 

Thanks, @weiyuan-jiang, I appreciate it.  But after a very quick review I am seeing changes only in ./Util/mk_restarts.  There, I don't see a comment that provides the science rationale for why `CLM4.5_veg_typs_fracs` is obsolete.  And I don't see any changes/comments at all in the ./Util/Raster where `CLM4.5_veg_typs_fracs` is created.  Rather than create a separate branch, maybe the full set of changes can be done across the present branch and the current make_bcs cleanup in https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/576.  But more work is definitely needed.

**Comment by weiyuan-jiang** [comment] 2022-05-06 16:25
Oh, right.  We should correct it in the first place that creates CLM4.5_veg_typs_fracs

**Comment by gmao-jkolassa** [comment] 2022-05-09 17:55
I just wanted to follow up on this and confirm that I should be making a new branch in which I will clean up everything related to CLM4.5_veg_typs_fracs and then make a PR to merge this branch into the current version of feature/rreichle/mk_restarts_cleanup. Is my understanding correct?

**Comment by weiyuan-jiang** [comment] 2022-05-09 17:58
Let me take care of this first. If I have question, I will ask for your help @gmao-jkolassa

**Comment by gmao-rreichle** [comment] 2023-06-29 13:41
Addressed in #576.  Closing this issue.

**Closed by gmao-rreichle** 2023-06-29 13:41 UTC
